name: Make changelog

on:
  push:
    branches:
      - beta

permissions:
  contents: write

jobs:
  make-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build changelog files
        uses: ./.github/actions/make-changelog
        with:
          plugin_file: cleantalk-bbpress-scan.php
          readme_file: readme.txt
          changelog_file: changelog.txt
          target_branch: beta
          matrix_server: ${{ secrets.MATRIX_SERVER }}
          matrix_room: ${{ secrets.MATRIX_GITHUB_WORKFLOW_FEED }}
          matrix_token: ${{ secrets.MATRIX_WORKFLOW_POSTER_TOKEN }}
